
package com.proyectocitas.model;

public enum Permiso {

    CREAR_USUARIOS,
    VER_USUARIOS,
    ACTUALIZAR_USUARIOS,
    DESACTIVAR_USUARIOS,

    CREAR_ROLES,
    VER_ROLES,
    ACTUALIZAR_ROLES,
    ELIMINAR_ROLES,
    ASIGNAR_ROLES,
    ASIGNAR_PERMISOS,

    CREAR_MEDICOS,
    VER_MEDICOS,
    ACTUALIZAR_MEDICOS,
    ELIMINAR_MEDICOS,

    CREAR_ESPECIALIDADES,
    VER_ESPECIALIDADES,
    ACTUALIZAR_ESPECIALIDADES,
    ELIMINAR_ESPECIALIDADES,

    CREAR_HORARIOS,
    VER_HORARIOS_DISPONIBLES,
    ACTUALIZAR_HORARIOS,
    ELIMINAR_HORARIOS,

    CREAR_CITA,
    VER_CITAS,
    VER_HISTORIAL,
    CANCELAR_CITA,

    REGISTRAR_DIAGNOSTICO
}