spring.application.name=citas-backend

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/citas_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

# JWT
jwt.secret=estaEsUnaClaveSecretaParaElProyectoDeCitasMedicas2026Segura
jwt.expiration=86400000